### ISSUE TITLE
Fase 3.10 - Atividade a ser entregue até 29.05 - Criar um modelo de dados completo do sistema Health Track no Oracle SQL Developer Data Modeler.

### ISSUE THREAD

**Issue by Daniel-Silva** [Daniel-Silva/healthtrack#12]
Agora a “brincadeira ficou séria”! Abra seu Oracle SQL Developer Data Modeler e crie um modelo de dados completo do sistema Health Track! A entrega deve ser composta por:

- Diagrama de Modelo Lógico

- Diagrama de Modelo Físico

- Scripts SQL de criação de tabelas

- Plano “B”: Diagramas em formato JPG ou PNG caso o seu projeto do Data Modeler não abra por aqui!

As informações que você precisa foram explanadas nas fases 1 e 2, tudo o que falamos até agora PODE E DEVE SER USADO. Não se esqueça de suas entregas até aqui: casos de uso, protótipos de tela, tudo isso auxilia na criação do modelo de dados.

O exercício de “Quais informações são indispensáveis (e, portanto, obrigatórias) e qual delas são desejáveis (e, portanto, opcionais?)” é por sua conta, use seu senso crítico!

Não deixe de fazer uma boa normalização! Como resolver dados compostos e multivalorados? E outras situações que deixem os dados redundantes? Mitigue tudo isso!

“Fui além dos dados passados nas fases 1 e 2, fiz isso no protótipo de telas e fiz no modelo. Está errado?” Não necessariamente! Se você acredita que o dado coletado é pertinente ao negócio (Health Track), ótima contribuição! No entanto, relembramos: todas as entregas a partir daqui precisam contemplar seu escopo diferenciado. O projeto final deverá ser entregue funcionando com estes acréscimos! Como sempre digo: se você topar, nós topamos!

Não quer usar o Oracle SQL Developer Data Modeler? Não tem problema! Embora nossos materiais didáticos estejam baseados nele, existem outras ferramentas de mercado tão boas quanto, você pode usar! No entanto, seja qual ferramenta for, pedimos que você sempre exporte o modelo em formato de imagem (como JPG ou PNG) porque seria inviável termos por aqui todas as ferramentas disponíveis.

Faça isso mesmo que você use o Data Modeler. Repare que, ao salvar o projeto em Data Modeler, ele cria um arquivo .dmd e uma pasta, com o mesmo nome de seu projeto. Precisamos de um ZIP com tudo isso! Apenas o arquivo .dmd NÃO GARANTE A VISUALIZAÇÃO DO PROJETO. Compacte em ZIP e nos mande tudo! Repetimos, aproveite e gere JPG ou PNG (a ferramenta gera facilmente) para usarmos como “plano B”... combinado?

Muito bem! Excelente atividade para você e, qualquer dúvida, estamos por aqui, ok?

**Comment by fmonfardini** [comment]
Segue, modelos dos DB Lógico, relacional e scripts em SQL para criação das tabelas.

Abraço.


[Scripts_SQL_HT.zip](https://github.com/Daniel-Silva/healthtrack/files/2013453/Scripts_SQL_HT.zip)
