### ISSUE TITLE
Fase 3.8 - Atividade a ser entregue até 24.05 - Desenvolver um modelo lógico para armazenar dados de uma agenda de contatos no Oracle SQL Developer Data Modeler.

### ISSUE THREAD

**Issue by Daniel-Silva** [Daniel-Silva/healthtrack#13]
Este é o momento de aplicar seu novo conhecimento em banco de dados na prática! Abra seu Oracle SQL Developer Data Modeler e crie um modelo lógico para armazenar os dados de uma agenda de contatos!

Use como referência a agenda de contatos de seu smartphone, seja ela Android ou iOS.

Que informações são úteis ao armazenar um contato? Quais informações são indispensáveis (e, portanto, obrigatórias) e qual delas são desejáveis (e, portanto, opcionais?).

Algumas informações como endereço e telefone são multivaloradas, ou seja, um único contato pode possuir vários endereços e telefones associados a ele! Essas informações costumam ser compostas (vários dados formando uma única informação). Como resolver isso? O capítulo seguinte propõe soluções e algumas pistas já foram deixadas até agora, gostaríamos que você tentasse resolver esses problemas!

Essa modelagem, com alguns ajustes, pode ser útil na modelagem seguinte, que será ainda mais desafiadora! Ou seja, dois coelhos com uma só cajadada!

Não quer usar o Oracle SQL Developer Data Modeler? Não tem problema! Embora nossos materiais didáticos estejam baseados nele, existem outras ferramentas de mercado tão boas quanto, você pode usar! No entanto, seja qual ferramenta for, pedimos que você sempre exporte o modelo em formato de imagem (como JPG ou PNG) porque seria inviável termos por aqui todas as ferramentas disponíveis.

Faça isso mesmo que você use o Data Modeler. Repare que ao salvar o projeto em Data Modeler, ele cria um arquivo .dmd e uma pasta com o mesmo nome de seu projeto. Precisamos de um ZIP com tudo isso! Apenas o arquivo .dmd NÃO GARANTE A VISUALIZAÇÃO DO PROJETO. Compacte em ZIP e nos mande tudo! Repetimos: aproveite e gere JPG ou PNG (a ferramenta gera facilmente) para usarmos como “plano B”... combinado?

Muito bem! Boa atividade. Qualquer dúvida, estamos por aqui, ok?

**Comment by fmonfardini** [comment]
Fala Daniel, compartilhando meu Modelo do Data Modeler, e já adianto que o meu está errado, era modelo lógico, eu fiz o relacional, que é um pouco mais completo. 

[AGENDA_FIAP_1.zip](https://github.com/Daniel-Silva/healthtrack/files/2013450/AGENDA_FIAP_1.zip)

Abraços
