### ISSUE TITLE
Fase 3.4 - Atividade a ser entregue até 17.05 - Desenvolver o diagrama de atividades do Health Track

### ISSUE THREAD

**Issue by Daniel-Silva** [Daniel-Silva/healthtrack#14]
Este é o momento de aplicar o conhecimento adquirido neste capítulo no projeto Health Track.

  Faça o seguinte: revise suas documentações de casos de uso. Revise a documentação de casos de uso entregue na fase anterior. Identifique os fluxos que ficaram mais extensos; considere Fluxo Principal, Fluxo Alternativo e de Exceção – quanto mais fluxos diferentes um caso de uso possui, mais complexo ele se torna! Separe os três mais extensos e transforme cada um deles em pelo menos um Diagrama de Atividades.

Falamos “pelo menos”, pois você pode utilizar uma subatividade para representar algo mais “macro” em algum deles e descrever o detalhamento em outro Diagrama de Atividades à parte. Você tem liberdade para isso.

Abra um arquivo no Microsoft Word, copie e cole a documentação de caso de uso eleita como complexa e, na sequência, o Diagrama (ou diagramas) de Atividades que a represente. Faça isso com as três eleitas, exporte como PDF e entregue para a gente!

Dúvidas? Procure-nos no fórum do FIAP ON ou no link “Converse com a gente”. Boa sorte!

**Comment by fmonfardini** [comment]
Fala Daniel, tava vendo seus projetos aqui no GitHub e curti, bem organizado o kanban, vou compartilhar com vc o meu diagrama, assim conseguimos trocar algumas ideias, para ver se estamos com a mesma linha raciocínio sobre á atividade.

Abraço.
![diagramadeatividadeii](https://user-images.githubusercontent.com/37197233/39925588-a2a97962-5502-11e8-8437-63dbecd0b5f4.png)
![diagramadeatividade](https://user-images.githubusercontent.com/37197233/39925589-a2c65dde-5502-11e8-9272-2cd285cc46ca.png)

**Comment by Daniel-Silva** [comment]
E ai mano, tranquilo?
Obrigado! Deu um pouco de trabalho pra organizar rsss...

Curti de mais seus diagramas e eu nem comecei os meus ainda. Vou tentar
adiantar hoje e compartilho contigo o que eu for fazendo.
Legal sua iniciativa, vamos mantendo contato para alinharmos as ideias.
Segue meu whats 11 98380-4055, qualquer coisa só chamar por lá.

Forte abraço!

Daniel Silva

Em 11 de maio de 2018 10:04, fmonfardini <notifications@github.com>
escreveu:

**Comment by Daniel-Silva** [comment]
Atividade concluída em 17.05
Elaborado diagrama de atividades 

[Diagrama de atividades - Health Track.pdf](https://github.com/Daniel-Silva/healthtrack/files/2023054/Diagrama.de.atividades.-.Health.Track.pdf)
